{% set name = "SHERPAS" %}
{% set version = "1.0.1" %}
{% set sha256 = "cd1d311ef27d30048e4907aae756948939e91a42954f1e2f6f8ae15222d40de2" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/phylo42/{{ name|lower }}/releases/download/{{version}}/{{version}}.tar.gz
  sha256: {{ sha256 }}

build:
  number: 0

requirements:
  build:
    - {{ compiler('cxx') }}
    - cmake
  host:
    - boost-cpp
  run:
    - boost-cpp

test:
  commands:
    - SHERPAS | grep "Let's go"

about:
  home: https://github.com/phylo42/sherpas
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: "Screening Historical Events of Recombination in a Phylogeny via Ancestral Sequences."
  description: "A new, alignment-free genome recombination detection tool exploiting the idea of phylo-kmers (Linard et al. 2019) to accelerate the process by several orders of magnitude while keeping comparable accuracy."

extra:
  identifiers:
    - doi:10.1101/2020.06.22.161422
